### ISSUE TITLE
5MB Background image too big

### ISSUE THREAD

**Issue by Velua** [EOS-Nation/bancor-ui#23]
Background image on the app is 5MB
@DenisCarriere you got a design guy or should I just hack at this on GIMP?
[https://bancor.eosnation.io/img/bg01.2a11cdbf.jpg](https://bancor.eosnation.io/img/bg01.2a11cdbf.jpg)

**Comment by Velua** [comment]
Reduced

**Comment by DenisCarriere** [comment]
Ya I agree, we should lower the size of all images

No designer was used
