### ISSUE TITLE
UI glitch in mobile 

### ISSUE THREAD

**Issue by chillsauce** [EOS-Nation/bancor-ui#36]
![AB6E13B9-1FBD-4C04-90BE-B4E864C7DFAA](https://user-images.githubusercontent.com/37008057/72355092-cd06a780-36b4-11ea-88d0-e49860fba0aa.png)

**Comment by Velua** [comment]
Just made some changes, let me know what you think at [XNation](https://xnation.io)

**Comment by DenisCarriere** [comment]
Looks good on mobile now
