### ISSUE TITLE
change the green/blue buttons on the pool screen, to a + / - similar to the way 1inch does it

### ISSUE THREAD

**Issue by chillsauce** [EOS-Nation/bancor-ui#38]
![188F3AC6-3305-4377-90E3-CA27545D6890](https://user-images.githubusercontent.com/37008057/72356307-0c35f800-36b7-11ea-826d-49a833706bd8.jpeg)

![A72D3F2B-F882-46A3-834E-FB7AB4FA0937](https://user-images.githubusercontent.com/37008057/72356329-15bf6000-36b7-11ea-9b07-96fe3b333804.jpeg)

**Comment by Velua** [comment]
Done
