### ISSUE TITLE
Website footer and privacy policy page

### ISSUE THREAD

**Issue by chillsauce** [EOS-Nation/bancor-ui#44]
add a footer to the website, similar to this:
![Screen Shot 2020-01-18 at 2 46 25 PM](https://user-images.githubusercontent.com/37008057/72669612-06674c00-3a02-11ea-832d-6f76e893240d.png)

link to eosnation.io and a new privacy policy page within xnation.io 

Create privacy policy using the content found here (replace EOS Nation with xNation) 
https://eosnation.io/privacy-policy/

**Comment by Velua** [comment]
Done
