### ISSUE TITLE
Convert values need to be refreshed after pressing the middle switch button

### ISSUE THREAD

**Issue by yogevmas** [EOS-Nation/bancor-ui#51]
To re-produce go to https://bancor.eosnation.io/eos  fill 1 EOS on the left. Now press the middle seitch button, it changes from EOS->BNT to BNT->EOS but keeps the same values in the fields which are wrong for the opposite conversion.

**Comment by Velua** [comment]
Thanks for pointing this out.

**Comment by Velua** [comment]
@yogevmas Fixed now, let me know if otherwise.
