### ISSUE TITLE
Handle ? : operations 

### ISSUE THREAD

**Issue by Velua** [EOS-Nation/bancor-ui#56]
Dependent on strategy, cases of ```currentNetwork == 'eos' ? this : that``` are existing to the code, this won't be friendly to a new network coming in like USD if it's being considered a "*network*"

**Comment by DenisCarriere** [comment]
You’ll need two categories

Network & Platform

“eos::bancor”
“eth::bancor”
“eos::sx”

That way ya you can also add the logic of the network & project

**Comment by Velua** [comment]
Refactoring has got us out of trouble, seperated network from wallet.
