### ISSUE TITLE
Safari Bug

### ISSUE THREAD

**Issue by Velua** [EOS-Nation/bancor-ui#60]
Does not work in Safari because BigInt

**Comment by Velua** [comment]
Pushed this through to beta, yet to actually test because I don't have an iPhone and left my Macbook at home.

**Comment by Velua** [comment]
Atm it's just a component that lets the user know Safari is not supported

**Comment by Velua** [comment]
@DenisCarriere @chillsauce 
Further ideas on this one? 

An attempt to display a page to advise the user to use another browser failed, I'm guessing because Safari freaks out at BigInt even being part of the code. 

Chrome for iOS fails too, so essentially iOS devices don't work at all. 

Can either push more time into detecting the browser and displaying a page or the polyfill, how much work do you think that would be @DenisCarriere ?

**Comment by DenisCarriere** [comment]
I think I found a solution for the BigInt issue

https://github.com/peterolson/BigInteger.js

This is used as a Polyfill

The syntax is slightly different, so I've got a few refactoring to do, but I've tested it out and it is looking promising

I should be able to convert eos-common into pure ES5 (old ass Javascript)

Once I finish refactoring the code and testing the library with all it's testcase, we should be able to get Safari and iOS Chrome fixed again without doing anything special

It should just be a dependency bump

**Comment by Velua** [comment]
> "It should just be a dependency bump"

\*Creates breaking update\*
https://github.com/EOS-Nation/eos-common/commit/10793e4323a7ce8f6bfbc2a9dbd282c10440e499

Lol, what's the strategy with this? I was using all those utils.

Can confirm however after updating the librarys Safari seems to be rendering again!

**Comment by Velua** [comment]
Awaiting sxjs update.

**Comment by Velua** [comment]
SXJS updated, deployed to beta.
