### ISSUE TITLE
Exclude pools which aren't in eos airdrop repo

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/bancor-ui#83]
Many accounts will most likely push test tokens or unauthoritative tokens.

An easy way to exclude fake tokens is to enforce all pools to also be included in the EOS Airdrops repo.

This would exclude `UVUVBNT` from our current list of pools.

**Comment by Velua** [comment]
Coded, pending release.

**Comment by Velua** [comment]
Now in beta, https://github.com/EOS-Nation/bancor-ui/releases/tag/v0.9
