### ISSUE TITLE
"Add token" hyperlink in create pool token modal

### ISSUE THREAD

**Issue by chillsauce** [EOS-Nation/bancor-ui#84]
Add a hyperlink to the token repository in the create pool token selection modal:
https://github.com/eoscafe/eos-airdrops

**Comment by Velua** [comment]
Coded, pending next release.

**Comment by Velua** [comment]
Released in https://github.com/EOS-Nation/bancor-ui/commit/cbea71fdf4267f93149eb5e7cab8b8baa9af9ce2
