### ISSUE TITLE
Still getting Bancor "insufficient balance" error

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/bancor-ui#91]
Even with the latest release, still getting the following error when adding liquidity to pool

![image](https://user-images.githubusercontent.com/550895/78062058-1d101480-735c-11ea-9bb2-bb86498f6fb5.png)

**Comment by DenisCarriere** [comment]
Might be because of rounding up numbers?

Try rounding down any divisions

**Comment by Velua** [comment]
Is this on the beta or prod version?

**Comment by Velua** [comment]
Because I engaged old mate you forwarded messages from and he said it's now working with the beta release, if not, can you tell me how much smart tokens scatter is trying to buy?
